version: "3"


services:
  remote-control-service:
    image: amatiashov/remote-control-service
    restart: always
    ports:
      - 80:8080
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./resources/:/usr/src/app/resources/
